### ISSUE TITLE
Link fails because of missing -ltoxmessenger

### ISSUE THREAD

**Issue by yurivict** [TokTok/toxins#4]
```
cc -O2 -pipe -fno-omit-frame-pointer  -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer -isystem /usr/local/include  -fstack-protector -L/usr/local/lib  -o tox_shell tox_shell.c ../util/misc_tools.c -static -ltoxcore -lsodium -lpthread -lutil
/usr/local/lib/libtoxcore.a(tox.c.o): In function `tox_new':
toxcore/tox.c:(.text+0xc3): undefined reference to `new_messenger'
```

**Comment by iphydf** [comment]
You'll need to get the latest master of toxcore. Any commit after https://github.com/TokTok/c-toxcore/commit/f2b6090eca42f4a364ef7517c5eec6d472e9b5f6 will do.

**Comment by yurivict** [comment]
I think, this is the fix: https://github.com/TokTok/toxins/pull/5

**Comment by iphydf** [comment]
No, the fix is to have a more recent version of toxcore. The small libraries version is gone, toxins don't support it.

**Comment by yurivict** [comment]
I have the latest version of toxcore installed: toxcore-0.1.11_1,1

Do you know when the new toxcore will be released?

(Asking because I tried to create a FreeBSD port for toxins, and can't use the latest version. The port has to use the installed version.).

**Comment by iphydf** [comment]
Ah, I see. 0.2.0 will be released soon. I hope we can get qtox working with it by next weekend. Then we can release it.

**Comment by yurivict** [comment]
Ok, thanks!

Closing it and will wait for the release.
